                
name: CI/CD-fxg3cgef90
on: 
  push:
 
jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-7gcx2zp9ku,v-699p00wpr8,v-q5sjvjv5ap]
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls

  build-image-v02:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-vecdws1ui7,v-bxrwr758oa,v-s6b8tmk7cc]
    continue-on-error: true
    needs: build-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls

  build-image-v03:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-chggotrdh6,v-huhlm5hbst,v-mbcdlyihml]
    continue-on-error: true
    needs: build-image-v02
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls

  build-image-v04:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-h1sie322lz,v-qt5mkzlyw0,v-ixzrjqrq3j]
    continue-on-error: true
    needs: build-image-v03
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls
